import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { cmsClient } from "../lib/api/cms-client";
import Link from "next/link";

type Blog = {
  id: string;
  title: string;
  body: string;
};

type Props = {
  blogs: Blog[];
};

const Home: NextPage<Props> = (props) => {
  const { blogs } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <ul>
          {blogs.map((blog) => {
            return (
              <li key={blog.id}>
                <Link href={`blog/${blog.id}`}>
                  <a>{blog.title}</a>
                </Link>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const res = await cmsClient.getList<Blog>({ endpoint: "blog" });
  return { props: { blogs: res.contents } };
};
